version: '3.8'
services:


  authservice:
    image: ghcr.io/chatgut/authservice2:latest
    container_name: auth
    depends_on:
      - auth-DB
    environment:
      DB_URL: auth-DB:3306/auth-DB1
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8003:8080"
  auth-DB:
    image: 'mysql:latest'
    container_name: auth-DB1
    volumes:
      - dbAuth:/var/lib/mysql
    environment:
      MYSQL_DATABASE: auth-DB1
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password


  like:
    image: cchriss123/worthreadingservice:arm64
    container_name: worthreadingservice
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8005:8005"
  like-DB:
    image: 'mysql:latest'
    container_name: like-Db
    volumes:
      - likeDbData:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5



  img:
    image: cchriss123/imageservice:arm64
    container_name: imageservice
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8001:8001"
  mysql:
    image: 'mysql:latest'
    container_name: img-Db
    volumes:
      - imgAppData:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3308:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5


  userservice:
    image: ghcr.io/chatgut/userservice:1.0
    ports:
      - "8002:8002"
    environment:
      DB_URL: jdbc:mysql://userservice-mysql:3306/userservice-mysql
      DB_USER: developer
      DB_PASSWORD: password
  userservice-mysql:
    image: "mysql:latest"
    container_name: userservice-mysql
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userservice-mysql
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_HOST: '%'
    ports:
      - "3309:3306"


  frontend:
    image: mikaeledwartz/webservice:chatgut
    container_name: frontend
    ports:
      - "8081:8080"

  app:
    image: cchriss123/post:latest
    container_name: postService
    restart: on-failure
    depends_on:
      - mongodb
      - rabbitMQ
    environment:
      ROCKET_DATABASES: '{postservice={url="mongodb://dbMongoDB:27017"}}'
      ROCKET_RABBIT_HOST: "amqp://QueueRabbitMQ:5672"

    ports:
      - "8000:8000"

  mongodb:
    image: 'mongo:latest'
    container_name: dbMongoDB
    volumes:
      - dbData:/var/lib/mongodb
    ports:
      - "27017:27017"

  rabbitMQ:
    image: 'rabbitmq:3-management'
    container_name: QueueRabbitMQ
    volumes:
      - dbData:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"




volumes:
  authDbData:
  likeDbData:
  imgAppData:
  db_mysql:
  dbAuth:
  dbData:
